# Tratamento de Exce√ß√µes no Java
O tratamento de exece√ß√µes √© o processo de lidar com **situa√ß√µes inesperadas ou erros que podem ocorrer durante a execu√ß√£o de um programa Java**. 
O objetivo principal √© **evitar que o programa finalize abruptamente** e permitir que ele continue funcionando, ou pelo menos forne√ßa uma mensagem de erro adequada ao usu√°rio. 

Ou seja:  

**‚úÖTratar os erros do Java, permite que o programa execute uma determinada l√≥gica caso o erro ocorra, al√©m de fazer com que o programa continue a execu√ß√£o.** 

**‚ùåN√£o tratar os erros causa a interrup√ß√£o do programa, prejudicando a experiencia do usu√°rio final.**



---

### üî∏`try-catch`

Basicamente funciona da seguinte forma:  
Dentro do `try` fica o **bloco de c√≥digo que pode gerar uma Exception**, enquanto o `catch` **fica respons√°vel por capturar e tratar essa Exception**:

```  
try {

  //BLOCO DE C√ìDIGO QUE √â MONITORADO PARA ERROS

} catch(TipoDaException exception) {

  //TRATAMENTO DO ERRO

}

```
---

### üî∏M√∫ltiplos `catch`  
Funciona da mesma forma que o `try catch` convencional por√©m **√© utilizado quando um bloco de c√≥digo pode gerar mais de uma Exception**:

```
try {

  //BLOCO DE C√ìDIGO QUE √â MONITORADO PARA ERROS

} catch(TipoDaException1 exception1) {

  //TRATAMENTO DO ERRO 1

} catch(TipoDaException2 exception2) {

  //TRATAMENTO DO ERRO 2

}
```

---

### üî∏M√∫tiplos `catch` de Exceptions da mesma fam√≠lia  

Quando temos que tratar **Exceptions que pertencem a mesma fam√≠lia**, ao inv√©s de utilizar v√°rios blocos `catch` seguidos, podemos utilizar apenas um bloco `catch` e declarar todas as Exceptions seguindo a seguinte sintaxe:  

```
try {

  //BLOCO DE C√ìDIGO QUE √â MONITORADO PARA ERROS

} catch(TipoDaException1 exception1 | TipoDaException2 exception2 | TipoDaException3 exception3) {

  //TRATAMENTO DO ERRO

}
```
---

### üî∏`try-catch-finally`  

O bloco `finally` em Java **√© usado para garantir que um determinado bloco de c√≥digo seja executado, independentemente de ocorrer uma exce√ß√£o ou n√£o dentro do bloco** `try`. √â frequentemente **utilizado para liberar recursos, como fechar arquivos ou conex√µes de banco de dados**, garantindo que esses recursos sejam sempre liberados, mesmo que ocorra um erro:

```  
try {

  //BLOCO DE C√ìDIGO QUE √â MONITORADO PARA ERROS

} catch(TipoDaException exception) {

  //TRATAMENTO DO ERRO

} finally {

  //EXECUTADO AP√ìS O BLOCO TRY OU CATCH

}
```
**OBSERVA√á√ÉO:** Como foi mencionado, o bloco `finally` √© executado SEMPRE, mesmo se houver um erro ou n√£o, por√©m a uma exce√ß√£o, caso seja passado o m√©todo `System.exit(int status)` dentro do bloco `catch`, e o mesmo for executado, o bloco `finally` e qualquer coisa que esteja depois n√£o ser√£o executados:  

```
try {

  //BLOCO DE C√ìDIGO QUE IR√Å GERAR UM ERRO

} catch(TipoDaException exception) {

  //TRATAMENTO DO ERRO
  System.exit(0);

} finally {

  //ESSE BLOCO NUNCA SER√Å EXECUTADO

}

System.out.println("ESSE COMANDO NUNCA SER√Å EXECUTADO");

```
---
### üî∏M√©todos da super classe `Throwable` utilizados no tratamento de Exceptions:  

`getMessage()` ‚û° retorna a descri√ß√£o do erro.  
`printStackTrace()` ‚û° imprime a _stack trace_ do erro

---

### `throws`

A palavra-chave `throws` √© **usada na declara√ß√£o de um m√©todo para indicar que esse m√©todo pode lan√ßar uma ou mais exce√ß√µes**. Em outras palavras, **ela informa ao c√≥digo que chama esse m√©todo que ele deve estar preparado para lidar com a possibilidade de uma exce√ß√£o ocorrer durante a execu√ß√£o do m√©todo**:

